_wandb:
    value:
        cli_version: 0.22.2
        e:
            up0qdhe4d94ygg8r6n3foepgc5heums1:
                args:
                    - --alpha=0.877994328051318
                    - --batch_size=16
                    - --beta=19.98344515715297
                    - --data_dir=data/windows_ieee33
                    - --device=cuda
                    - --dropout=0
                    - --epochs=60
                    - --gnn_hidden=64
                    - --gnn_layers=3
                    - --hidden_dim=128
                    - --lambda_op=1
                    - --lr=0.0001
                    - --num_layers=2
                    - --save_dir=checkpoints
                    - --tag=W96
                    - --wandb_project=GridSE_PGR
                    - --weight_decay=0.0001
                codePath: train/train_pgr_hybrid.py
                codePathLocal: train/train_pgr_hybrid.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "119138906112"
                email: a530029885@gmail.com
                executable: /home/wzseu/anaconda3/envs/jjc_gm/bin/python
                git:
                    commit: 63968637aab0637ec7e2986a758e800fd317e2c4
                    remote: https://github.com/ERIC-JJC1/GM-SE.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-df9f4d1d-c942-2049-c297-2b04f2cbaa13
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-710f46d9-de5e-0b0d-2c9b-8e9ea520a688
                host: wzseu-Z790-EAGLE-AX
                memory:
                    total: "202431541248"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wzseu/JJC_project/wls_33/train/train_pgr_hybrid.py
                python: CPython 3.10.18
                root: /home/wzseu/JJC_project/wls_33
                startedAt: "2025-10-25T16:05:25.534621Z"
                writerId: up0qdhe4d94ygg8r6n3foepgc5heums1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 1
                - 2
                - 13
                - 14
                - 16
                - 62
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: 0.877994328051318
batch_size:
    value: 16
beta:
    value: 19.98344515715297
data_dir:
    value: data/windows_ieee33
device:
    value: cuda
dropout:
    value: 0
epochs:
    value: 60
gnn_dropout:
    value: 0
gnn_hidden:
    value: 64
gnn_layers:
    value: 3
hidden_dim:
    value: 128
lambda_op:
    value: 1
lambda_pf:
    value: 0.1
lambda_smooth:
    value: 0.01
lr:
    value: 0.0001
num_layers:
    value: 2
save_dir:
    value: checkpoints
seed:
    value: 42
tag:
    value: W96
wandb_group:
    value: null
wandb_name:
    value: null
wandb_project:
    value: GridSE_PGR
weight_decay:
    value: 0.0001
