wandb_version: 1

batch_size:
  value: 32
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
epochs:
  value: 60
gnn_hidden:
  value: 128
gnn_layers:
  value: 3
hidden_dim:
  value: 256
lambda_op:
  value: 0.1
lr:
  value: 0.001
num_layers:
  value: 3
save_dir:
  value: checkpoints
seed:
  value: 42
tag:
  value: W24
w_temp_th:
  value: 0
w_temp_vm:
  value: 0
wandb_project:
  value: GridSE_TAGRU_Weakly
