_wandb:
    value:
        cli_version: 0.22.2
        e:
            hdwd0lhogfc7lru7njmdiub6ofso5oi0:
                args:
                    - --epochs
                    - "2"
                    - --batch_size
                    - "4"
                    - --data_dir
                    - data/windows_ieee33
                    - --alpha
                    - "1.0"
                    - --beta
                    - "10.0"
                    - --tag
                    - W24
                codePath: train/train_pgr_hybrid.py
                codePathLocal: train/train_pgr_hybrid.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "118115500032"
                email: a530029885@gmail.com
                executable: /home/wzseu/anaconda3/envs/jjc_gm/bin/python
                git:
                    commit: 99e4f72c10815c72465f46973ad07a5deffc026b
                    remote: https://github.com/ERIC-JJC1/GM-SE.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-df9f4d1d-c942-2049-c297-2b04f2cbaa13
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-710f46d9-de5e-0b0d-2c9b-8e9ea520a688
                host: wzseu-Z790-EAGLE-AX
                memory:
                    total: "202431541248"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wzseu/JJC_project/wls_33/train/train_pgr_hybrid.py
                python: CPython 3.10.18
                root: /home/wzseu/JJC_project/wls_33
                startedAt: "2025-10-22T12:26:43.810266Z"
                writerId: hdwd0lhogfc7lru7njmdiub6ofso5oi0
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 1
                - 16
                - 17
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: 1
batch_size:
    value: 4
beta:
    value: 10
data_dir:
    value: data/windows_ieee33
device:
    value: cuda
epochs:
    value: 2
gnn_hidden:
    value: 128
gnn_layers:
    value: 2
hidden_dim:
    value: 256
lambda_op:
    value: 1
lr:
    value: 0.0005
num_layers:
    value: 2
save_dir:
    value: checkpoints
seed:
    value: 42
tag:
    value: W24
wandb_project:
    value: PGR_Hybrid_Training
