wandb_version: 1

batch_size:
  value: 16
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
epochs:
  value: 60
hidden_dim:
  value: 256
lr:
  value: 0.0001
model_type:
  value: gru
num_layers:
  value: 2
save_dir:
  value: checkpoints
seed:
  value: 42
tag:
  value: W24
wandb_project:
  value: GridSE_GRU_Baseline
