_wandb:
    value:
        cli_version: 0.22.2
        e:
            v7x889u4vjiz7snphl4gqh9bxxl8wwid:
                args:
                    - --epochs
                    - "100"
                    - --batch_size
                    - "32"
                    - --lr
                    - "1e-3"
                    - --hidden_dim
                    - "256"
                    - --num_layers
                    - "2"
                    - --data_dir
                    - data/windows_ieee33
                    - --tag
                    - W24
                    - --save_dir
                    - checkpoints
                    - --wandb_project
                    - RefineWLS_Training
                    - --seed
                    - "42"
                codePath: train/train_refine_baseline.py
                codePathLocal: train/train_refine_baseline.py
                email: a530029885@gmail.com
                executable: /home/wzseu/anaconda3/envs/jjc_gm/bin/python
                git:
                    commit: ea8da8904e65ecb6380b8447175c444a9de6e77d
                    remote: https://github.com/ERIC-JJC1/GM-SE.git
                host: wzseu-Z790-EAGLE-AX
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wzseu/JJC_project/wls_33/train/train_refine_baseline.py
                python: CPython 3.10.18
                root: /home/wzseu/JJC_project/wls_33
                startedAt: "2025-10-25T01:41:56.852977Z"
                writerId: v7x889u4vjiz7snphl4gqh9bxxl8wwid
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 16
                - 17
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 32
data_dir:
    value: data/windows_ieee33
device:
    value: cuda
epochs:
    value: 100
gnn_hidden:
    value: 128
gnn_layers:
    value: 2
hidden_dim:
    value: 256
lambda_phys:
    value: 0
lr:
    value: 0.001
num_layers:
    value: 2
save_dir:
    value: checkpoints
seed:
    value: 42
tag:
    value: W24
w_temp_th:
    value: 0
w_temp_vm:
    value: 0
wandb_project:
    value: RefineWLS_Training
