wandb_version: 1

alpha:
  value: 0.16299911337076056
batch_size:
  value: 32
beta:
  value: 19.408863907879315
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0
epochs:
  value: 60
gnn_hidden:
  value: 128
gnn_layers:
  value: 3
hidden_dim:
  value: 256
lambda_op:
  value: 1
lr:
  value: 0.0005
num_layers:
  value: 2
save_dir:
  value: checkpoints
tag:
  value: W96
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0
