_wandb:
    value:
        cli_version: 0.22.2
        e:
            3t7ce2bmvvhbztbiw7vbg6eumcqxsqm5:
                args:
                    - --batch_size=32
                    - --data_dir=data/windows_ieee33
                    - --device=cuda
                    - --epochs=60
                    - --gnn_hidden=128
                    - --gnn_layers=2
                    - --hidden_dim=128
                    - --lr=0.001
                    - --nhead=8
                    - --num_layers=2
                    - --save_dir=checkpoints
                    - --seed=42
                    - --tag=W24
                    - --use_gnn=False
                    - --wandb_project=GridSE_RefineSeq
                codePath: train/train_refine_baseline.py
                codePathLocal: train/train_refine_baseline.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "118980382720"
                email: a530029885@gmail.com
                executable: /home/wzseu/anaconda3/envs/jjc_gm/bin/python
                git:
                    commit: 63968637aab0637ec7e2986a758e800fd317e2c4
                    remote: https://github.com/ERIC-JJC1/GM-SE.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-df9f4d1d-c942-2049-c297-2b04f2cbaa13
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-710f46d9-de5e-0b0d-2c9b-8e9ea520a688
                host: wzseu-Z790-EAGLE-AX
                memory:
                    total: "202431541248"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wzseu/JJC_project/wls_33/train/train_refine_baseline.py
                python: CPython 3.10.18
                root: /home/wzseu/JJC_project/wls_33
                startedAt: "2025-10-25T15:11:18.775648Z"
                writerId: 3t7ce2bmvvhbztbiw7vbg6eumcqxsqm5
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 14
                - 16
                - 17
                - 62
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 32
bias_scale:
    value: 3
data_dir:
    value: data/windows_ieee33
device:
    value: cuda
epochs:
    value: 60
gnn_dropout:
    value:
        - 0
gnn_hidden:
    value: 128
gnn_layers:
    value: 2
gnn_type:
    value: tag
hidden_dim:
    value: 128
lambda_phys:
    value: 0
lr:
    value: 0.001
nhead:
    value: 8
num_layers:
    value: 2
num_workers:
    value: 0
save_dir:
    value: checkpoints
seed:
    value: 42
tag:
    value: W24
use_bus_smooth:
    value: true
use_gnn:
    value: false
use_mask:
    value: false
w_temp_th:
    value: 0
w_temp_vm:
    value: 0
wandb_project:
    value: GridSE_RefineSeq
