wandb_version: 1

alpha:
  value: 1.2654498725356151
batch_size:
  value: 32
beta:
  value: 10.043836223967762
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0
epochs:
  value: 60
gnn_hidden:
  value: 64
gnn_layers:
  value: 2
hidden_dim:
  value: 256
lambda_op:
  value: 0.1
lr:
  value: 0.0001
num_layers:
  value: 2
save_dir:
  value: checkpoints
tag:
  value: W24
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0.0001
