wandb_version: 1

alpha:
  value: 1.1472367977262936
batch_size:
  value: 32
beta:
  value: 19.226873528831927
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0.2
epochs:
  value: 60
gnn_hidden:
  value: 64
gnn_layers:
  value: 2
hidden_dim:
  value: 128
lambda_op:
  value: 1
lr:
  value: 0.0001
num_layers:
  value: 2
save_dir:
  value: checkpoints
tag:
  value: W96
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0.0001
