_wandb:
    value:
        cli_version: 0.22.2
        e:
            uhec36hk4cp1ck30je59r7xnw0mco7rm:
                args:
                    - --alpha=1.1192481407428738
                    - --batch_size=16
                    - --beta=19.28026520213804
                    - --data_dir=data/windows_ieee33
                    - --device=cuda
                    - --dropout=0.2
                    - --epochs=60
                    - --gnn_hidden=128
                    - --gnn_layers=3
                    - --hidden_dim=256
                    - --lambda_op=0.1
                    - --lr=0.001
                    - --num_layers=3
                    - --save_dir=checkpoints
                    - --tag=W96
                    - --wandb_project=GridSE_PGR
                    - --weight_decay=0.0001
                codePath: train/train_pgr_hybrid.py
                codePathLocal: train/train_pgr_hybrid.py
                email: a530029885@gmail.com
                executable: /home/wzseu/anaconda3/envs/jjc_gm/bin/python
                git:
                    commit: 63968637aab0637ec7e2986a758e800fd317e2c4
                    remote: https://github.com/ERIC-JJC1/GM-SE.git
                host: wzseu-Z790-EAGLE-AX
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wzseu/JJC_project/wls_33/train/train_pgr_hybrid.py
                python: CPython 3.10.18
                root: /home/wzseu/JJC_project/wls_33
                startedAt: "2025-10-25T12:54:35.651682Z"
                writerId: uhec36hk4cp1ck30je59r7xnw0mco7rm
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 14
                - 16
                - 17
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: 1.1192481407428738
batch_size:
    value: 16
beta:
    value: 19.28026520213804
data_dir:
    value: data/windows_ieee33
device:
    value: cuda
dropout:
    value: 0.2
epochs:
    value: 60
gnn_hidden:
    value: 128
gnn_layers:
    value: 3
hidden_dim:
    value: 256
lambda_op:
    value: 0.1
lr:
    value: 0.001
num_layers:
    value: 3
save_dir:
    value: checkpoints
seed:
    value: 42
tag:
    value: W96
wandb_project:
    value: GridSE_PGR
weight_decay:
    value: 0.0001
