wandb_version: 1

alpha:
  value: 1.974403795076128
batch_size:
  value: 32
beta:
  value: 11.409264265603824
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0
epochs:
  value: 60
gnn_hidden:
  value: 64
gnn_layers:
  value: 3
hidden_dim:
  value: 128
lambda_op:
  value: 0.1
lr:
  value: 0.0001
num_layers:
  value: 2
save_dir:
  value: checkpoints
tag:
  value: W96
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0
