wandb_version: 1

alpha:
  value: 1.5365332818413937
batch_size:
  value: 16
beta:
  value: 16.08099337523398
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 60
gnn_hidden:
  value: 64
gnn_layers:
  value: 3
hidden_dim:
  value: 256
lambda_op:
  value: 1
lr:
  value: 0.0005
num_layers:
  value: 3
save_dir:
  value: checkpoints
tag:
  value: W96
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0
