wandb_version: 1

alpha:
  value: 1.292014949108902
batch_size:
  value: 16
beta:
  value: 14.459990376923264
data_dir:
  value: data/windows_ieee33
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 60
gnn_hidden:
  value: 64
gnn_layers:
  value: 3
hidden_dim:
  value: 256
lambda_op:
  value: 1
lr:
  value: 0.0005
num_layers:
  value: 3
save_dir:
  value: checkpoints
tag:
  value: W96
wandb_project:
  value: GridSE_PGR
weight_decay:
  value: 0.0001
